### Get
GET http://localhost:3001/api/persons

### GetId
GET http://localhost:3001/api/persons/66f69fbf0c1dd30206874519

### GetId "not found"
GET http://localhost:3001/api/persons/77f5759e9137a5e5c4923a65

### Delete
DELETE http://localhost:3001/api/persons/66f5759e9137a5e5c4923a65

### Post
POST http://localhost:3001/api/persons
Content-Type: application/json

    {
        "name": "casemiro arnaldo",
        "number": 1212345678
    }

### Post without a  name

POST http://localhost:3001/api/persons
Content-Type: application/json

    {
        "number": "12-12345678"
    }
### Put
PUT http://localhost:3001/api/persons/66f69fbf0c1dd30206874519

{
    "number": 123456789
}